spring:
  datasource:
    url: jdbc:postgresql://db:5432/ carservice
    username: postgres
    password: 1234
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # session:
  #   store-type: none
  #   cookie:
  #     http-only: true
  #     secure: true
  #     same-site: strict

# server:
#   port: 8080
#   servlet:
#     context-path: /api

logging:
  level:
    org.springframework.security: DEBUG
    com.vehicleservice: DEBUG 